// Complete list of German KFZ-Kennzeichen
// Source: Wikipedia "Liste der Kfz-Kennzeichen in Deutschland"

export const STATES = {
  'BW': 'Baden-Württemberg',
  'BY': 'Bayern',
  'BE': 'Berlin',
  'BB': 'Brandenburg',
  'HB': 'Bremen',
  'HH': 'Hamburg',
  'HE': 'Hessen',
  'MV': 'Mecklenburg-Vorpommern',
  'NI': 'Niedersachsen',
  'NW': 'Nordrhein-Westfalen',
  'RP': 'Rheinland-Pfalz',
  'SL': 'Saarland',
  'SN': 'Sachsen',
  'ST': 'Sachsen-Anhalt',
  'SH': 'Schleswig-Holstein',
  'TH': 'Thüringen'
};

export const KENNZEICHEN = [
  // Baden-Württemberg
  { code: "AA", name: "Ostalbkreis (Aalen)", state: "BW" },
  { code: "BAD", name: "Baden-Baden", state: "BW" },
  { code: "BB", name: "Böblingen", state: "BW" },
  { code: "BC", name: "Biberach an der Riß", state: "BW" },
  { code: "BL", name: "Zollernalbkreis (Balingen)", state: "BW" },
  { code: "BLB", name: "Schwarzwald-Baar-Kreis (Villingen-Schwenningen)", state: "BW" },
  { code: "BÜS", name: "Büsingen am Hochrhein", state: "BW" },
  { code: "CW", name: "Calw", state: "BW" },
  { code: "DS", name: "Donaueschingen", state: "BW" },
  { code: "EM", name: "Emmendingen", state: "BW" },
  { code: "ES", name: "Esslingen am Neckar", state: "BW" },
  { code: "FDS", name: "Freudenstadt", state: "BW" },
  { code: "FN", name: "Bodenseekreis (Friedrichshafen)", state: "BW" },
  { code: "FR", name: "Freiburg im Breisgau", state: "BW" },
  { code: "GP", name: "Göppingen", state: "BW" },
  { code: "HD", name: "Heidelberg / Rhein-Neckar-Kreis", state: "BW" },
  { code: "HDH", name: "Heidenheim an der Brenz", state: "BW" },
  { code: "HN", name: "Heilbronn", state: "BW" },
  { code: "KA", name: "Karlsruhe", state: "BW" },
  { code: "KEL", name: "Kehl", state: "BW" },
  { code: "KN", name: "Konstanz", state: "BW" },
  { code: "KÜN", name: "Hohenlohekreis (Künzelsau)", state: "BW" },
  { code: "LB", name: "Ludwigsburg", state: "BW" },
  { code: "LEO", name: "Leonberg", state: "BW" },
  { code: "LÖ", name: "Lörrach", state: "BW" },
  { code: "MOS", name: "Neckar-Odenwald-Kreis (Mosbach)", state: "BW" },
  { code: "TBB", name: "Main-Tauber-Kreis (Tauberbischofsheim)", state: "BW" },
  { code: "MÜL", name: "Müllheim", state: "BW" },
  { code: "NT", name: "Nürtingen", state: "BW" },
  { code: "NÜ", name: "Nürtingen (alt)", state: "BW" },
  { code: "OG", name: "Ortenaukreis (Offenburg)", state: "BW" },
  { code: "PF", name: "Pforzheim / Enzkreis", state: "BW" },
  { code: "RA", name: "Rastatt", state: "BW" },
  { code: "RT", name: "Reutlingen", state: "BW" },
  { code: "RV", name: "Ravensburg", state: "BW" },
  { code: "RW", name: "Rottweil", state: "BW" },
  { code: "S", name: "Stuttgart", state: "BW" },
  { code: "SHA", name: "Schwäbisch Hall", state: "BW" },
  { code: "SIG", name: "Sigmaringen", state: "BW" },
  { code: "TÜ", name: "Tübingen", state: "BW" },
  { code: "TUT", name: "Tuttlingen", state: "BW" },
  { code: "UL", name: "Ulm / Alb-Donau-Kreis", state: "BW" },
  { code: "VS", name: "Schwarzwald-Baar-Kreis (Villingen-Schwenningen)", state: "BW" },
  { code: "WN", name: "Rems-Murr-Kreis (Waiblingen)", state: "BW" },
  { code: "WT", name: "Waldshut", state: "BW" },

  // Bayern
  { code: "A", name: "Augsburg", state: "BY" },
  { code: "AB", name: "Aschaffenburg", state: "BY" },
  { code: "AIC", name: "Aichach-Friedberg", state: "BY" },
  { code: "ALT", name: "Altötting", state: "BY" },
  { code: "AM", name: "Amberg", state: "BY" },
  { code: "AN", name: "Ansbach", state: "BY" },
  { code: "AÖ", name: "Altötting", state: "BY" },
  { code: "AS", name: "Amberg-Sulzbach", state: "BY" },
  { code: "BA", name: "Bamberg", state: "BY" },
  { code: "BGL", name: "Berchtesgadener Land", state: "BY" },
  { code: "BT", name: "Bayreuth", state: "BY" },
  { code: "BUL", name: "Burglengenfeld", state: "BY" },
  { code: "CHA", name: "Cham", state: "BY" },
  { code: "CO", name: "Coburg", state: "BY" },
  { code: "DAH", name: "Dachau", state: "BY" },
  { code: "DEG", name: "Deggendorf", state: "BY" },
  { code: "DGF", name: "Dingolfing-Landau", state: "BY" },
  { code: "DKB", name: "Dinkelbühl", state: "BY" },
  { code: "DLG", name: "Dillingen an der Donau", state: "BY" },
  { code: "DON", name: "Donau-Ries (Donauwörth)", state: "BY" },
  { code: "EBE", name: "Ebersberg", state: "BY" },
  { code: "ED", name: "Erding", state: "BY" },
  { code: "EI", name: "Eichstätt", state: "BY" },
  { code: "ER", name: "Erlangen", state: "BY" },
  { code: "ERH", name: "Erlangen-Höchstadt", state: "BY" },
  { code: "ESB", name: "Eschenbach in der Oberpfalz", state: "BY" },
  { code: "FDB", name: "Friedberg (Bayern)", state: "BY" },
  { code: "FEU", name: "Feuchtwangen", state: "BY" },
  { code: "FFB", name: "Fürstenfeldbruck", state: "BY" },
  { code: "FO", name: "Forchheim", state: "BY" },
  { code: "FRG", name: "Freyung-Grafenau", state: "BY" },
  { code: "FS", name: "Freising", state: "BY" },
  { code: "FÜ", name: "Fürth", state: "BY" },
  { code: "GAP", name: "Garmisch-Partenkirchen", state: "BY" },
  { code: "GRA", name: "Grafenau", state: "BY" },
  { code: "GRI", name: "Griesbach im Rottal", state: "BY" },
  { code: "GUN", name: "Gunzenhausen", state: "BY" },
  { code: "GZ", name: "Günzburg", state: "BY" },
  { code: "HAS", name: "Haßberge (Haßfurt)", state: "BY" },
  { code: "HEB", name: "Hersbruck", state: "BY" },
  { code: "HIP", name: "Hilpoltstein", state: "BY" },
  { code: "HO", name: "Hof", state: "BY" },
  { code: "IN", name: "Ingolstadt", state: "BY" },
  { code: "KC", name: "Kronach", state: "BY" },
  { code: "KE", name: "Kempten (Allgäu)", state: "BY" },
  { code: "KEH", name: "Kelheim", state: "BY" },
  { code: "KF", name: "Kaufbeuren", state: "BY" },
  { code: "KG", name: "Bad Kissingen", state: "BY" },
  { code: "KT", name: "Kitzingen", state: "BY" },
  { code: "KU", name: "Kulmbach", state: "BY" },
  { code: "LA", name: "Landshut", state: "BY" },
  { code: "LAU", name: "Nürnberger Land (Lauf)", state: "BY" },
  { code: "LI", name: "Lindau (Bodensee)", state: "BY" },
  { code: "LIF", name: "Lichtenfels", state: "BY" },
  { code: "LL", name: "Landsberg am Lech", state: "BY" },
  { code: "M", name: "München", state: "BY" },
  { code: "MAI", name: "Mainburg", state: "BY" },
  { code: "MAL", name: "Mallersdorf", state: "BY" },
  { code: "MET", name: "Mellrichstadt", state: "BY" },
  { code: "MIL", name: "Miltenberg", state: "BY" },
  { code: "MM", name: "Memmingen", state: "BY" },
  { code: "MN", name: "Unterallgäu (Mindelheim)", state: "BY" },
  { code: "MÜ", name: "Mühldorf am Inn", state: "BY" },
  { code: "MSP", name: "Main-Spessart", state: "BY" },
  { code: "N", name: "Nürnberg", state: "BY" },
  { code: "NAB", name: "Nabburg", state: "BY" },
  { code: "ND", name: "Neuburg-Schrobenhausen", state: "BY" },
  { code: "NEA", name: "Neustadt an der Aisch-Bad Windsheim", state: "BY" },
  { code: "NEW", name: "Neustadt an der Waldnaab", state: "BY" },
  { code: "NM", name: "Neumarkt in der Oberpfalz", state: "BY" },
  { code: "NÖ", name: "Neuötting", state: "BY" },
  { code: "OA", name: "Oberallgäu", state: "BY" },
  { code: "OAL", name: "Ostallgäu", state: "BY" },
  { code: "OBB", name: "Obernburg am Main", state: "BY" },
  { code: "OVI", name: "Oberviechtach", state: "BY" },
  { code: "PA", name: "Passau", state: "BY" },
  { code: "PAF", name: "Pfaffenhofen an der Ilm", state: "BY" },
  { code: "PAN", name: "Rottal-Inn (Pfarrkirchen)", state: "BY" },
  { code: "PAR", name: "Parsberg", state: "BY" },
  { code: "PEG", name: "Pegnitz", state: "BY" },
  { code: "R", name: "Regensburg", state: "BY" },
  { code: "REG", name: "Regen", state: "BY" },
  { code: "REH", name: "Rehau", state: "BY" },
  { code: "RID", name: "Riedenburg", state: "BY" },
  { code: "RO", name: "Rosenheim", state: "BY" },
  { code: "ROD", name: "Roding", state: "BY" },
  { code: "ROL", name: "Rottenburg an der Laaber", state: "BY" },
  { code: "RH", name: "Roth", state: "BY" },
  { code: "SC", name: "Schwabach", state: "BY" },
  { code: "SEB", name: "Selb", state: "BY" },
  { code: "SMÜ", name: "Schwabmünchen", state: "BY" },
  { code: "SOG", name: "Schongau", state: "BY" },
  { code: "SR", name: "Straubing-Bogen / Straubing", state: "BY" },
  { code: "STA", name: "Starnberg", state: "BY" },
  { code: "SUL", name: "Sulzbach-Rosenberg", state: "BY" },
  { code: "SW", name: "Schweinfurt", state: "BY" },
  { code: "TIR", name: "Tirschenreuth", state: "BY" },
  { code: "TÖL", name: "Bad Tölz-Wolfratshausen", state: "BY" },
  { code: "TS", name: "Traunstein", state: "BY" },
  { code: "VOH", name: "Vohenstrauß", state: "BY" },
  { code: "WEN", name: "Weiden in der Oberpfalz", state: "BY" },
  { code: "WÜ", name: "Würzburg", state: "BY" },
  { code: "WM", name: "Weilheim-Schongau", state: "BY" },
  { code: "WOR", name: "Wolfratshausen", state: "BY" },
  { code: "WS", name: "Wasserburg am Inn", state: "BY" },
  { code: "WUG", name: "Weißenburg-Gunzenhausen", state: "BY" },
  { code: "WUN", name: "Wunsiedel im Fichtelgebirge", state: "BY" },

  // Berlin
  { code: "B", name: "Berlin", state: "BE" },

  // Brandenburg
  { code: "BAR", name: "Barnim", state: "BB" },
  { code: "BRB", name: "Brandenburg an der Havel", state: "BB" },
  { code: "CB", name: "Cottbus", state: "BB" },
  { code: "EE", name: "Elbe-Elster", state: "BB" },
  { code: "FF", name: "Frankfurt (Oder)", state: "BB" },
  { code: "HVL", name: "Havelland", state: "BB" },
  { code: "LDS", name: "Dahme-Spreewald", state: "BB" },
  { code: "LOS", name: "Oder-Spree", state: "BB" },
  { code: "MOL", name: "Märkisch-Oderland", state: "BB" },
  { code: "OHV", name: "Oberhavel", state: "BB" },
  { code: "OPR", name: "Ostprignitz-Ruppin", state: "BB" },
  { code: "OSL", name: "Oberspreewald-Lausitz", state: "BB" },
  { code: "P", name: "Potsdam", state: "BB" },
  { code: "PM", name: "Potsdam-Mittelmark", state: "BB" },
  { code: "PR", name: "Prignitz", state: "BB" },
  { code: "SPN", name: "Spree-Neiße", state: "BB" },
  { code: "TF", name: "Teltow-Fläming", state: "BB" },
  { code: "UM", name: "Uckermark", state: "BB" },

  // Bremen
  { code: "HB", name: "Bremen", state: "HB" },

  // Hamburg
  { code: "HH", name: "Hamburg", state: "HH" },

  // Hessen
  { code: "DA", name: "Darmstadt / Darmstadt-Dieburg", state: "HE" },
  { code: "DI", name: "Darmstadt-Dieburg (Dieburg)", state: "HE" },
  { code: "ERB", name: "Odenwaldkreis (Erbach)", state: "HE" },
  { code: "ESW", name: "Werra-Meißner-Kreis (Eschwege)", state: "HE" },
  { code: "F", name: "Frankfurt am Main", state: "HE" },
  { code: "FB", name: "Wetteraukreis (Friedberg)", state: "HE" },
  { code: "FD", name: "Fulda", state: "HE" },
  { code: "FK", name: "Frankenberg (Eder)", state: "HE" },
  { code: "GG", name: "Groß-Gerau", state: "HE" },
  { code: "GI", name: "Gießen", state: "HE" },
  { code: "GN", name: "Gelnhausen", state: "HE" },
  { code: "HP", name: "Bergstraße (Heppenheim)", state: "HE" },
  { code: "HR", name: "Schwalm-Eder-Kreis (Homberg)", state: "HE" },
  { code: "HU", name: "Main-Kinzig-Kreis (Hanau)", state: "HE" },
  { code: "HEF", name: "Hersfeld-Rotenburg", state: "HE" },
  { code: "KB", name: "Waldeck-Frankenberg (Korbach)", state: "HE" },
  { code: "KS", name: "Kassel", state: "HE" },
  { code: "LDK", name: "Lahn-Dill-Kreis", state: "HE" },
  { code: "LM", name: "Limburg-Weilburg", state: "HE" },
  { code: "MKK", name: "Main-Kinzig-Kreis", state: "HE" },
  { code: "MR", name: "Marburg-Biedenkopf", state: "HE" },
  { code: "MTK", name: "Main-Taunus-Kreis", state: "HE" },
  { code: "OF", name: "Offenbach am Main / Landkreis Offenbach", state: "HE" },
  { code: "RÜD", name: "Rheingau-Taunus-Kreis (Rüdesheim)", state: "HE" },
  { code: "SLÜ", name: "Schlüchtern", state: "HE" },
  { code: "VB", name: "Vogelsbergkreis", state: "HE" },
  { code: "WI", name: "Wiesbaden", state: "HE" },
  { code: "WZ", name: "Wetzlar", state: "HE" },

  // Mecklenburg-Vorpommern
  { code: "ANK", name: "Anklam", state: "MV" },
  { code: "DBR", name: "Bad Doberan", state: "MV" },
  { code: "DM", name: "Demmin", state: "MV" },
  { code: "GÜ", name: "Güstrow", state: "MV" },
  { code: "GVM", name: "Grevesmühlen", state: "MV" },
  { code: "HGW", name: "Greifswald", state: "MV" },
  { code: "HRO", name: "Rostock", state: "MV" },
  { code: "HST", name: "Stralsund", state: "MV" },
  { code: "HWI", name: "Wismar", state: "MV" },
  { code: "LBZ", name: "Lübz", state: "MV" },
  { code: "LRO", name: "Landkreis Rostock", state: "MV" },
  { code: "LUP", name: "Ludwigslust-Parchim", state: "MV" },
  { code: "MSE", name: "Mecklenburgische Seenplatte", state: "MV" },
  { code: "MST", name: "Müritz (Waren)", state: "MV" },
  { code: "MÜR", name: "Müritz", state: "MV" },
  { code: "NB", name: "Neubrandenburg", state: "MV" },
  { code: "NVP", name: "Nordvorpommern", state: "MV" },
  { code: "NWM", name: "Nordwestmecklenburg", state: "MV" },
  { code: "OVP", name: "Ostvorpommern", state: "MV" },
  { code: "PCH", name: "Parchim", state: "MV" },
  { code: "RDG", name: "Ribnitz-Damgarten", state: "MV" },
  { code: "RÜG", name: "Rügen", state: "MV" },
  { code: "SN", name: "Schwerin", state: "MV" },
  { code: "UER", name: "Uecker-Randow", state: "MV" },
  { code: "VG", name: "Vorpommern-Greifswald", state: "MV" },
  { code: "VR", name: "Vorpommern-Rügen", state: "MV" },
  { code: "WLG", name: "Wolgast", state: "MV" },

  // Niedersachsen
  { code: "AUR", name: "Aurich", state: "NI" },
  { code: "BRA", name: "Wesermarsch (Brake)", state: "NI" },
  { code: "BS", name: "Braunschweig", state: "NI" },
  { code: "BÜR", name: "Büren", state: "NW" },
  { code: "CE", name: "Celle", state: "NI" },
  { code: "CLP", name: "Cloppenburg", state: "NI" },
  { code: "CUX", name: "Cuxhaven", state: "NI" },
  { code: "DAN", name: "Lüchow-Dannenberg", state: "NI" },
  { code: "DEL", name: "Delmenhorst", state: "NI" },
  { code: "DH", name: "Diepholz", state: "NI" },
  { code: "EL", name: "Emsland", state: "NI" },
  { code: "EMD", name: "Emden", state: "NI" },
  { code: "FRI", name: "Friesland (Jever)", state: "NI" },
  { code: "GF", name: "Gifhorn", state: "NI" },
  { code: "GÖ", name: "Göttingen", state: "NI" },
  { code: "GS", name: "Goslar", state: "NI" },
  { code: "H", name: "Hannover (Region)", state: "NI" },
  { code: "HE", name: "Helmstedt", state: "NI" },
  { code: "HI", name: "Hildesheim", state: "NI" },
  { code: "HM", name: "Hameln-Pyrmont", state: "NI" },
  { code: "HOL", name: "Holzminden", state: "NI" },
  { code: "LER", name: "Leer", state: "NI" },
  { code: "NI", name: "Nienburg (Weser)", state: "NI" },
  { code: "NOH", name: "Grafschaft Bentheim (Nordhorn)", state: "NI" },
  { code: "NOM", name: "Northeim", state: "NI" },
  { code: "OHZ", name: "Osterholz", state: "NI" },
  { code: "OL", name: "Oldenburg", state: "NI" },
  { code: "OS", name: "Osnabrück", state: "NI" },
  { code: "OHA", name: "Osterode am Harz", state: "NI" },
  { code: "PE", name: "Peine", state: "NI" },
  { code: "ROW", name: "Rotenburg (Wümme)", state: "NI" },
  { code: "SFA", name: "Soltau-Fallingbostel", state: "NI" },
  { code: "SHG", name: "Schaumburg", state: "NI" },
  { code: "SZ", name: "Salzgitter", state: "NI" },
  { code: "SOB", name: "Schrobenhausen", state: "BY" },
  { code: "STD", name: "Stade", state: "NI" },
  { code: "UE", name: "Uelzen", state: "NI" },
  { code: "VEC", name: "Vechta", state: "NI" },
  { code: "VER", name: "Verden", state: "NI" },
  { code: "WF", name: "Wolfenbüttel", state: "NI" },
  { code: "WHV", name: "Wilhelmshaven", state: "NI" },
  { code: "WL", name: "Harburg (Winsen/Luhe)", state: "NI" },
  { code: "WOB", name: "Wolfsburg", state: "NI" },
  { code: "WST", name: "Ammerland (Westerstede)", state: "NI" },
  { code: "WTM", name: "Wittmund", state: "NI" },

  // Nordrhein-Westfalen
  { code: "AC", name: "Aachen / Städteregion Aachen", state: "NW" },
  { code: "BI", name: "Bielefeld", state: "NW" },
  { code: "BK", name: "Borken", state: "NW" },
  { code: "BM", name: "Rhein-Erft-Kreis (Bergheim)", state: "NW" },
  { code: "BN", name: "Bonn", state: "NW" },
  { code: "BO", name: "Bochum", state: "NW" },
  { code: "BOR", name: "Borken", state: "NW" },
  { code: "BOT", name: "Bottrop", state: "NW" },
  { code: "COE", name: "Coesfeld", state: "NW" },
  { code: "D", name: "Düsseldorf", state: "NW" },
  { code: "DN", name: "Düren", state: "NW" },
  { code: "DO", name: "Dortmund", state: "NW" },
  { code: "DU", name: "Duisburg", state: "NW" },
  { code: "E", name: "Essen", state: "NW" },
  { code: "EN", name: "Ennepe-Ruhr-Kreis", state: "NW" },
  { code: "EU", name: "Euskirchen", state: "NW" },
  { code: "GE", name: "Gelsenkirchen", state: "NW" },
  { code: "GL", name: "Rheinisch-Bergischer Kreis (Bergisch Gladbach)", state: "NW" },
  { code: "GM", name: "Oberbergischer Kreis (Gummersbach)", state: "NW" },
  { code: "GT", name: "Gütersloh", state: "NW" },
  { code: "HA", name: "Hagen", state: "NW" },
  { code: "HAM", name: "Hamm", state: "NW" },
  { code: "HER", name: "Herne", state: "NW" },
  { code: "HF", name: "Herford", state: "NW" },
  { code: "HS", name: "Heinsberg", state: "NW" },
  { code: "HSK", name: "Hochsauerlandkreis", state: "NW" },
  { code: "HX", name: "Höxter", state: "NW" },
  { code: "K", name: "Köln", state: "NW" },
  { code: "KLE", name: "Kleve", state: "NW" },
  { code: "KR", name: "Krefeld", state: "NW" },
  { code: "LEV", name: "Leverkusen", state: "NW" },
  { code: "LIP", name: "Lippe (Detmold)", state: "NW" },
  { code: "ME", name: "Mettmann", state: "NW" },
  { code: "MG", name: "Mönchengladbach", state: "NW" },
  { code: "MH", name: "Mülheim an der Ruhr", state: "NW" },
  { code: "MI", name: "Minden-Lübbecke", state: "NW" },
  { code: "MK", name: "Märkischer Kreis", state: "NW" },
  { code: "MS", name: "Münster", state: "NW" },
  { code: "NE", name: "Rhein-Kreis Neuss", state: "NW" },
  { code: "OB", name: "Oberhausen", state: "NW" },
  { code: "OE", name: "Olpe", state: "NW" },
  { code: "PB", name: "Paderborn", state: "NW" },
  { code: "RE", name: "Recklinghausen", state: "NW" },
  { code: "RS", name: "Remscheid", state: "NW" },
  { code: "SG", name: "Solingen", state: "NW" },
  { code: "SI", name: "Siegen-Wittgenstein", state: "NW" },
  { code: "SO", name: "Soest", state: "NW" },
  { code: "ST", name: "Steinfurt", state: "NW" },
  { code: "SU", name: "Rhein-Sieg-Kreis (Siegburg)", state: "NW" },
  { code: "UN", name: "Unna", state: "NW" },
  { code: "VIE", name: "Viersen", state: "NW" },
  { code: "W", name: "Wuppertal", state: "NW" },
  { code: "WAF", name: "Warendorf", state: "NW" },
  { code: "WES", name: "Wesel", state: "NW" },

  // Rheinland-Pfalz
  { code: "AK", name: "Altenkirchen (Westerwald)", state: "RP" },
  { code: "AW", name: "Ahrweiler", state: "RP" },
  { code: "AZ", name: "Alzey-Worms", state: "RP" },
  { code: "BIR", name: "Birkenfeld", state: "RP" },
  { code: "BIT", name: "Bitburg-Prüm", state: "RP" },
  { code: "COC", name: "Cochem-Zell", state: "RP" },
  { code: "DAU", name: "Vulkaneifel (Daun)", state: "RP" },
  { code: "DÜW", name: "Bad Dürkheim", state: "RP" },
  { code: "EMS", name: "Rhein-Lahn-Kreis (Bad Ems)", state: "RP" },
  { code: "FT", name: "Frankenthal (Pfalz)", state: "RP" },
  { code: "GER", name: "Germersheim", state: "RP" },
  { code: "KH", name: "Bad Kreuznach", state: "RP" },
  { code: "KIB", name: "Donnersbergkreis (Kirchheimbolanden)", state: "RP" },
  { code: "KL", name: "Kaiserslautern", state: "RP" },
  { code: "KO", name: "Koblenz", state: "RP" },
  { code: "KUS", name: "Kusel", state: "RP" },
  { code: "LD", name: "Landau in der Pfalz", state: "RP" },
  { code: "LU", name: "Ludwigshafen am Rhein", state: "RP" },
  { code: "MYK", name: "Mayen-Koblenz", state: "RP" },
  { code: "MZ", name: "Mainz / Mainz-Bingen", state: "RP" },
  { code: "NR", name: "Neuwied", state: "RP" },
  { code: "NW", name: "Neustadt an der Weinstraße", state: "RP" },
  { code: "PS", name: "Pirmasens", state: "RP" },
  { code: "RP", name: "Rhein-Pfalz-Kreis", state: "RP" },
  { code: "SIM", name: "Rhein-Hunsrück-Kreis (Simmern)", state: "RP" },
  { code: "SP", name: "Speyer", state: "RP" },
  { code: "SÜW", name: "Südliche Weinstraße", state: "RP" },
  { code: "TR", name: "Trier / Trier-Saarburg", state: "RP" },
  { code: "WIL", name: "Bernkastel-Wittlich (Wittlich)", state: "RP" },
  { code: "WO", name: "Worms", state: "RP" },
  { code: "WW", name: "Westerwaldkreis", state: "RP" },
  { code: "ZW", name: "Zweibrücken", state: "RP" },

  // Saarland
  { code: "HOM", name: "Saarpfalz-Kreis (Homburg)", state: "SL" },
  { code: "IGB", name: "St. Ingbert", state: "SL" },
  { code: "MZG", name: "Merzig-Wadern", state: "SL" },
  { code: "NK", name: "Neunkirchen", state: "SL" },
  { code: "SB", name: "Saarbrücken (Regionalverband)", state: "SL" },
  { code: "SLS", name: "Saarlouis", state: "SL" },
  { code: "WND", name: "St. Wendel", state: "SL" },

  // Sachsen
  { code: "BED", name: "Brand-Erbisdorf", state: "SN" },
  { code: "BIW", name: "Bischofswerda", state: "SN" },
  { code: "BNA", name: "Borna", state: "SN" },
  { code: "C", name: "Chemnitz", state: "SN" },
  { code: "DD", name: "Dresden", state: "SN" },
  { code: "DL", name: "Döbeln", state: "SN" },
  { code: "DW", name: "Dippoldiswalde", state: "SN" },
  { code: "DZ", name: "Delitzsch", state: "SN" },
  { code: "ERZ", name: "Erzgebirgskreis", state: "SN" },
  { code: "FG", name: "Freiberg", state: "SN" },
  { code: "FLÖ", name: "Flöha", state: "SN" },
  { code: "GC", name: "Chemnitzer Land (Glauchau)", state: "SN" },
  { code: "GR", name: "Görlitz", state: "SN" },
  { code: "GRH", name: "Großenhain", state: "SN" },
  { code: "HC", name: "Hohenstein-Ernstthal", state: "SN" },
  { code: "L", name: "Leipzig", state: "SN" },
  { code: "MEI", name: "Meißen", state: "SN" },
  { code: "MW", name: "Mittweida", state: "SN" },
  { code: "NOL", name: "Niederschlesischer Oberlausitzkreis", state: "SN" },
  { code: "PIR", name: "Sächsische Schweiz-Osterzgebirge (Pirna)", state: "SN" },
  { code: "RIE", name: "Riesa", state: "SN" },
  { code: "STL", name: "Stollberg", state: "SN" },
  { code: "TDO", name: "Torgau-Oschatz", state: "SN" },
  { code: "TO", name: "Torgau", state: "SN" },
  { code: "V", name: "Vogtlandkreis (Plauen)", state: "SN" },
  { code: "Z", name: "Zwickau", state: "SN" },
  { code: "ZP", name: "Zschopau", state: "SN" },

  // Sachsen-Anhalt
  { code: "ABI", name: "Anhalt-Bitterfeld", state: "ST" },
  { code: "ASL", name: "Aschersleben", state: "ST" },
  { code: "AZE", name: "Anhalt-Zerbst", state: "ST" },
  { code: "BLK", name: "Burgenlandkreis", state: "ST" },
  { code: "BÖ", name: "Börde", state: "ST" },
  { code: "BTF", name: "Bernburg", state: "ST" },
  { code: "DE", name: "Dessau-Roßlau", state: "ST" },
  { code: "GAR", name: "Gardelegen", state: "ST" },
  { code: "HAL", name: "Halle (Saale)", state: "ST" },
  { code: "HBS", name: "Halberstadt", state: "ST" },
  { code: "HET", name: "Hettstedt", state: "ST" },
  { code: "HZ", name: "Harz", state: "ST" },
  { code: "JL", name: "Jerichower Land", state: "ST" },
  { code: "KÖT", name: "Köthen (Anhalt)", state: "ST" },
  { code: "MD", name: "Magdeburg", state: "ST" },
  { code: "ML", name: "Mansfeld-Südharz", state: "ST" },
  { code: "MSH", name: "Mansfeld-Südharz", state: "ST" },
  { code: "NMB", name: "Naumburg", state: "ST" },
  { code: "OC", name: "Oschersleben", state: "ST" },
  { code: "QLB", name: "Quedlinburg", state: "ST" },
  { code: "ROS", name: "Roßlau", state: "ST" },
  { code: "SAW", name: "Altmarkkreis Salzwedel", state: "ST" },
  { code: "SBK", name: "Schönebeck", state: "ST" },
  { code: "SDL", name: "Stendal", state: "ST" },
  { code: "SGH", name: "Sangerhausen", state: "ST" },
  { code: "SK", name: "Saalekreis", state: "ST" },
  { code: "SLK", name: "Salzlandkreis", state: "ST" },
  { code: "SSW", name: "Staßfurt", state: "ST" },
  { code: "WB", name: "Wittenberg", state: "ST" },
  { code: "WR", name: "Wernigerode", state: "ST" },
  { code: "WSL", name: "Weißenfels", state: "ST" },
  { code: "ZE", name: "Zerbst", state: "ST" },
  { code: "ZZ", name: "Zeitz", state: "ST" },

  // Schleswig-Holstein
  { code: "EC", name: "Eckernförde", state: "SH" },
  { code: "FL", name: "Flensburg", state: "SH" },
  { code: "HEI", name: "Dithmarschen (Heide)", state: "SH" },
  { code: "HL", name: "Lübeck", state: "SH" },
  { code: "IZ", name: "Steinburg (Itzehoe)", state: "SH" },
  { code: "KI", name: "Kiel", state: "SH" },
  { code: "NF", name: "Nordfriesland", state: "SH" },
  { code: "NMS", name: "Neumünster", state: "SH" },
  { code: "OD", name: "Stormarn (Bad Oldesloe)", state: "SH" },
  { code: "OH", name: "Ostholstein", state: "SH" },
  { code: "PI", name: "Pinneberg", state: "SH" },
  { code: "PLÖ", name: "Plön", state: "SH" },
  { code: "RD", name: "Rendsburg-Eckernförde", state: "SH" },
  { code: "RZ", name: "Herzogtum Lauenburg (Ratzeburg)", state: "SH" },
  { code: "SE", name: "Segeberg", state: "SH" },
  { code: "SL", name: "Schleswig-Flensburg", state: "SH" },

  // Thüringen
  { code: "ABG", name: "Altenburger Land", state: "TH" },
  { code: "APD", name: "Apolda", state: "TH" },
  { code: "ARN", name: "Arnstadt", state: "TH" },
  { code: "EA", name: "Eisenach", state: "TH" },
  { code: "EF", name: "Erfurt", state: "TH" },
  { code: "EIC", name: "Eichsfeld", state: "TH" },
  { code: "ESA", name: "Eisenach", state: "TH" },
  { code: "G", name: "Gera", state: "TH" },
  { code: "GRZ", name: "Greiz", state: "TH" },
  { code: "GTH", name: "Gotha", state: "TH" },
  { code: "HBN", name: "Hildburghausen", state: "TH" },
  { code: "IK", name: "Ilm-Kreis", state: "TH" },
  { code: "J", name: "Jena", state: "TH" },
  { code: "KYF", name: "Kyffhäuserkreis", state: "TH" },
  { code: "LSZ", name: "Bad Langensalza", state: "TH" },
  { code: "MGN", name: "Meiningen", state: "TH" },
  { code: "MHL", name: "Mühlhausen", state: "TH" },
  { code: "NDH", name: "Nordhausen", state: "TH" },
  { code: "RU", name: "Rudolstadt", state: "TH" },
  { code: "SHL", name: "Suhl", state: "TH" },
  { code: "SLF", name: "Saalfeld-Rudolstadt", state: "TH" },
  { code: "SLZ", name: "Bad Salzungen", state: "TH" },
  { code: "SM", name: "Schmalkalden-Meiningen", state: "TH" },
  { code: "SOK", name: "Saale-Orla-Kreis", state: "TH" },
  { code: "SON", name: "Sonneberg", state: "TH" },
  { code: "SRO", name: "Stadtroda", state: "TH" },
  { code: "SÖM", name: "Sömmerda", state: "TH" },
  { code: "UH", name: "Unstrut-Hainich-Kreis", state: "TH" },
  { code: "WAK", name: "Wartburgkreis", state: "TH" },
  { code: "WE", name: "Weimar", state: "TH" },
  { code: "AP", name: "Weimarer Land (Apolda)", state: "TH" },
  { code: "SHK", name: "Saale-Holzland-Kreis", state: "TH" },
];

// Deduplicate by code (keep first occurrence)
const seen = new Set();
const unique = [];
for (const kz of KENNZEICHEN) {
  if (!seen.has(kz.code)) {
    seen.add(kz.code);
    unique.push(kz);
  }
}
unique.sort((a, b) => a.code.localeCompare(b.code));

export { unique as default };
export const ALL_STATES = Object.entries(STATES).map(([code, name]) => ({ code, name })).sort((a, b) => a.name.localeCompare(b.name));
